#!/bin/bash

# Run triggers only on updates
if [ ! -e "/usr/local/tulio/data/users/admin" ]; then
	exit
fi

# Create a new Backup folder
TULIO_BACKUP="/root/hst_nginx_backups/$(date +%d%m%Y%H%M)"
mkdir -p TULIO_BACKUP

# Create a backup of the current configuration
cp -r /usr/local/tulio/nginx/conf/nginx.conf $TULIO_BACKUP/nginx.conf

exit
