#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/tulio/data/users/" ]; then
	exit
fi

# Prevent running and causes issues with outdated tulio version
if ! id "tulioweb" &> /dev/null; then
	exit
fi

# Check if preinstall hook exists
if [ -e "/etc/tuliocp/hooks/php/pre_install.sh" ]; then
	/etc/tuliocp/hooks/php/pre_install.sh
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$TULIO" ]; then
	export TULIO='/usr/local/tulio'
	PATH=$PATH:/usr/local/tulio/bin
	export PATH
fi

# Load upgrade functions and variables
source /usr/local/tulio/func/main.sh
source /usr/local/tulio/func/upgrade.sh
source /usr/local/tulio/conf/tulio.conf
source /usr/local/tulio/install/upgrade/upgrade.conf

# Restart tulio service
if [ -f "/etc/init.d/tulio" ]; then
	systemctl restart tulio > /dev/null 2>&1
fi

# Check if preinstall hook exists
if [ -e "/etc/tuliocp/hooks/php/post_install.sh" ]; then
	/etc/tuliocp/hooks/php/post_install.sh
fi
