#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/tulio/data/users/admin" ]; then
	exit
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$TULIO" ]; then
	export TULIO='/usr/local/tulio'
	PATH=$PATH:/usr/local/tulio/bin
	export PATH
fi

# Load upgrade functions and variables
source /usr/local/tulio/func/main.sh
source /usr/local/tulio/func/upgrade.sh
source /usr/local/tulio/conf/tulio.conf
source /usr/local/tulio/install/upgrade/upgrade.conf

# Restart tulio-web-terminal service if enabled
if [ -f "/etc/systemd/system/tulio-web-terminal.service" ]; then
	systemctl daemon-reload > /dev/null 2>&1
	if systemctl is-enabled tulio-web-terminal > /dev/null 2>&1; then
		systemctl restart tulio-web-terminal
	fi
fi
